version: "3.8"

services:
  api:
    build: .
    container_name: vendingmachine-api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vendingmachine-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    volumes:
      - ./frontend:/app

